@startuml "プロジェクト管理"

|利用者|
start
:ログイン;

|ホーム画面|
#palegreen:Myプロジェクト一覧画面|
#skyblue:Myプロジェクト一覧表示;

if (新しいプロジェクトの作成) is (新規作成ボタン) then
    #palegreen:新規プロジェクト作成画面|
    #skyblue:プロジェクト新規登録;
    |利用者|
    #pink:プロジェクト情報/
    |ホーム画面|
    #palegreen:プロジェクトホーム画面|
    end
endif

if (既存のプロジェクトへ移動) is (Myプロジェクトの選択) then
    #palegreen:プロジェクトホーム画面|
    end
endif

:左ナビゲーションメニュー;
split
    #palegreen:プロジェクト検索画面|
    #skyblue:プロジェクト検索;
    :検索したプロジェクトの選択;
    #palegreen:プロジェクトホーム画面|
    end
    
endsplit

@enduml