@startuml "アクター"

package PK_01 as "管理" {
    actor AC_0101 as "システム管理者"
}

package PK_02 as "プロジェクト人員" {
    actor AC_0201 as "プロジェクト管理者"
    actor AC_0202 as "プロジェクト従事者"
}

package PK_03 as "ステークホルダ" {
    actor AC_0301 as "オーナー"
    actor AC_0302 as "承認者"
}

@enduml