@startuml "アカウント管理"

|利用者|
start

|トップ画面|
#palegreen:トップ画面|
while (ユーザ登録済み) is (未登録)
    #skyblue:アカウント登録;
    |利用者|
    #pink:アカウント情報/
    |トップ画面|
endwhile (登録済み)
:ログイン;

|ホーム画面|
#palegreen:ホーム画面|

:画面右上のメニュー操作;
split
    :ログアウト;
    |トップ画面|
    end
    |ホーム画面|
split again
    |アカウント設定画面|
    #palegreen:アカウント設定画面|

    split
        #skyblue:アカウント削除;
        |トップ画面|
        end
        |アカウント設定画面|
    split again
        #skyblue:アカウント更新;
        end
    endsplit
    

endsplit

@enduml